### ISSUE TITLE
Missing arguments in json

### ISSUE THREAD

**Issue by HenryBaby** [Nonary/PlayNiteWatcher#1]
Heya!

I don't know if this has to do with the version of Sunshine that I am running (v0.20.0). But when the script is run, upon inserting the correct arguments in the apps.json, it seems as though it's required that the below arguments also be added.

These seems to be the default values, so if you try and edit the profile(s) from within Sunshine's webGUI, it appears as though they are set, but the actual functionality will have no effect.

"exclude-global-prep-cmd": "false",
"elevated": "false"

**Comment by Nonary** [comment]
All of the arguments in Sunshine since 0.19 are now optional, so they don't have to be set. The WebUI still sets them as their default non-null values, but it doesn't harm anything by omitting them entirely. This includes do and undo commands, you can have a do command without an undo for clarification.

Elevated parameter is for launching the game with administrator rights, typically this is not required unless you're playing a game that relies on anti-cheat such as Genshin Impact.

Because of security concerns with enabling elevated permissions, users will have to manually edit that value to true (either through the file or webUI).

**Comment by HenryBaby** [comment]
You're ofc right, my apologies. Upon further testing the functionality wasn't working even after adding the values manually. So I suppose it's a bug in Sunshine or something on my end.

Again, apologies ♥️

**Comment by Nonary** [comment]
> You're ofc right, my apologies. Upon further testing the functionality wasn't working even after adding the values manually. So I suppose it's a bug in Sunshine or something on my end.
> 
> Again, apologies ♥️

If you edit the values manually, Sunshine has to be restarted in order to recognize the changes. It caches the configuration in  memory when it is launched. Updating it in the webUI will refresh that cache, but external edits are not recognized until restart.

**Comment by HenryBaby** [comment]
> If you edit the values manually, Sunshine has to be restarted in order to recognize the changes. It caches the configuration in memory when it is launched. Updating it in the webUI will refresh that cache, but external edits are not recognized until restart.

Good point. Pretty sure I tried restarting after manually changing the apps.json. I'll give it another try from the webUI.
