### ISSUE TITLE
is there a way to launch the game directly without involving Playnite?

### ISSUE THREAD

**Issue by thinh105** [Nonary/PlayNiteWatcher#11]
That tool is incredible! I discovered it through the Sunshine AIO tool from these sources: https://github.com/LeGeRyChEeSe/Sunshine-AIO#sunshine-aio and reddit: https://www.reddit.com/r/MoonlightStreaming/comments/1f97vv7/sunshineaio_v011dev/ thanks to @LeGeRyChEeSe

I’ve been using your tool, and it works quite well overall.

However, I’ve noticed that it seems to automatically switch Playnite before launching the game. This results in a series of flashes when starting from the Moonlight client: first, my desktop appears, then Playnite in normal mode, and finally the game itself.

Is this the normal behavior of the tool? Are there any workarounds to bypass, hide, or minimize the flashing? Perhaps there’s a way to launch the game directly without involving Playnite?

The flashing is quite distracting and interrupts the flow, which can be quite annoying.

Thank you once again for the amazing tool and for providing an experience we never knew we needed. Your work is truly appreciated!

**Comment by Nonary** [comment]
Enable the "Start Playnite minimized" option in Playnite
1. Open Playnite.
2. Go to **Settings** (usually accessible via the gear icon or the menu).
3. In the settings menu, find the **General** tab.
4. Look for the option that says **Start Playnite minimized** and enable it by checking the box.
5. Save the changes.

Playnite is essential for the script to work because it detects when games are opened or closed, which the script relies on to function properly.
