### ISSUE TITLE
Issue with covers

### ISSUE THREAD

**Issue by MisterGabal** [Nonary/PlayNiteWatcher#9]
When importing Playnite covers into Sunshine the image size is sometimes wrong (it only shows the upper left quadrant of the cover). 
![Screenshot_2024-05-29-16-51-43-800_com limelight](https://github.com/Nonary/PlayNiteWatcher/assets/82838118/4eb4d60d-3d02-4dae-a2d1-9dc5013c7252)

**Comment by MichaelMKenny** [comment]
Could you look inside the folders in: `AppData\Local\Sunshine Playnite App Export\Apps`, and check the images aren't cut off there? That's the source of the artwork that Moonlight displays. Also, if they do look alright, could you tell me the dimensions of one of them?

**Comment by MisterGabal** [comment]
They were also cut off in that folder. When the images were not cropped, the size is also variable, some are 600x800,

**Comment by Nonary** [comment]
This looks like an issue caused by high DPI scaling on the phone if I had to guess, it looks like you have the phone zoom set to high? Can you try it with normal zoom settings? I am not sure where that is on android

**Comment by MisterGabal** [comment]
It is not an Android problem as the images are stored in that format in the Windows folders.

**Comment by Nonary** [comment]
> It is not an Android problem as the images are stored in that format in the Windows folders.

You are misunderstanding, the image you showed to me appears to be an android client, perhaps with accessibility features enabled such as large text. I am wondering if it is that setting which is causing the images to be broken when rendered on the android client side.

One way to confirm that would be to install Moonlight on the Windows host itself and connect it, if the images appear correct on Windows, then you know it is an android specific bug and should be reported to the moonlight-android issues instead.

**Comment by WinstonAqua** [comment]
Hello, I'm also experiencing the same issue as OP and I think I found the cause for this which is the image format JPG that gets cropped and the PNG format is safely kept as it is regardless of its aspect ratio. 
![photo_2024-06-11_16-44-08](https://github.com/Nonary/PlayNiteWatcher/assets/25696812/267cf4a1-3404-4e9b-9aa3-980776cb04ef)

This screenshot right here is on the latest Moonlight client on iOS and no there's nothing related to the screen ratio, because I got the same error on my Google TV which is also latest version and I never changed something in the accessibility features and 3-4 weeks earlier it worked flawlessly. 

As an example let's take 1 good looking game cover (that seems to have the good cover image and not stretched weirdly or cropped)  like MK8 Deluxe  and then a bad cropped game cover like:  Marvel Spider-Man Remastered and compare their formats, size, image aspect ratio accordingly: 
![Cover comparison](https://github.com/Nonary/PlayNiteWatcher/assets/25696812/4fd2f4f2-c5ea-4822-bd7d-daa430e56269)
I compared 10 bad games covers with also 10 other good games cover and this is the only thing that changes drastically and is a common point, the JPG format that gets broke.

**Comment by Nonary** [comment]
@WinstonAqua @MisterGabal 

Can you see if this works? Go to the Playnite Installation folder and then go to \Extensions\SunshineAppExport

Replace the file contained in this zip folder.

NOTE: You will have to unblock the file first, right click the zip after it is downloaded and go to properties, then unblock.

[SunshineAppExport.zip](https://github.com/user-attachments/files/15893819/SunshineAppExport.zip)

Once done, press F12 while Playnite is open and try exporting the games again, let me know if that fixed the portraits

**Comment by WinstonAqua** [comment]
The fix works now, I tried with an JPG cover image and this time it worked perfectly! Thanks a lot!

**Comment by MichaelMKenny** [comment]
The fix should be live now in the Playnite Add-ons
